# Generated by Django 4.1.3 on 2022-11-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='rt',
            field=models.DateTimeField(null=True),
        ),
    ]
