# Generated by Django 4.1.3 on 2022-11-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_alter_timer_rt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='timer',
            name='rt',
            field=models.IntegerField(default=0),
        ),
    ]
