# Generated by Django 4.1.3 on 2022-11-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_remove_timer_end_time_remove_timer_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='rt',
        ),
        migrations.AddField(
            model_name='timer',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
