# Generated by Django 4.1.3 on 2022-11-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_todo_delete_timer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
